name: CI

on:
    pull_request:
    push:
        branches:
            - master
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    
    php-74-alpine:
        name: "PHP 7.4 / Alpine"
        runs-on: ubuntu-18.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:7.4
            TRAVIS: 1

        steps:
            - uses: actions/checkout@v2

            - name: Install apt-packages
              run: |
                  sudo apt-get install apache2-utils

            - name: Install docker-compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Run docker
              run: |
                  #git clone https://github.com/spryker/docker-sdk.git ./docker
                  git clone https://github.com/elmerdigital/docker-sdk.git -b node16npm8 --single-branch docker

                  docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
                  docker/sdk up -t
                  docker/sdk testing console queue:worker:start --stop-when-empty
                  docker/sdk testing codecept run -c codeception.acceptance.yml

    php-80-alpine:
        name: "PHP 8.0 / Alpine"
        runs-on: ubuntu-18.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:8.0-alpine3.16
            TRAVIS: 1

        steps:
            - uses: actions/checkout@v2

            - name: Install apt-packages
              run: |
                  sudo apt-get install apache2-utils

            - name: Install docker-compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Run docker
              run: |
                  #git clone https://github.com/spryker/docker-sdk.git ./docker
                  git clone https://github.com/elmerdigital/docker-sdk.git -b node16npm8 --single-branch docker

                  docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
                  docker/sdk up -t
                  docker/sdk testing console queue:worker:start --stop-when-empty
                  docker/sdk testing codecept run -c codeception.acceptance.yml


    php-80-debian:
        name: "PHP 8.0 / Debian"
        runs-on: ubuntu-18.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:8.0-debian
            TRAVIS: 1

        steps:
            - uses: actions/checkout@v2

            - name: Install apt-packages
              run: |
                  sudo apt-get install apache2-utils

            - name: Install docker-compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Run docker
              run: |
                  #git clone https://github.com/spryker/docker-sdk.git ./docker
                  git clone https://github.com/elmerdigital/docker-sdk.git -b node16npm8 --single-branch docker

                  docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
                  docker/sdk up -t
                  docker/sdk testing console queue:worker:start --stop-when-empty
                  docker/sdk testing codecept run -c codeception.acceptance.yml


    php-80-debian-buster:
        name: "PHP 8.0 / Debian / Buster"
        runs-on: ubuntu-18.04
        env:
            PROGRESS_TYPE: plain
            SPRYKER_PLATFORM_IMAGE: spryker/php:8.0-debian-buster
            TRAVIS: 1

        steps:
            - uses: actions/checkout@v2

            - name: Install apt-packages
              run: |
                  sudo apt-get install apache2-utils

            - name: Install docker-compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Run docker
              run: |
                  #git clone https://github.com/spryker/docker-sdk.git ./docker
                  git clone https://github.com/elmerdigital/docker-sdk.git -b node16npm8 --single-branch docker

                  docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
                  docker/sdk up -t
                  docker/sdk testing console queue:worker:start --stop-when-empty
                  docker/sdk testing codecept run -c codeception.acceptance.yml

